[project]
name = "sql-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.10"
dependencies = [
    "igraph>=0.11.9",
    "sqlglot>=26.31.0",
]
