// source: formula_parser.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var dtypes_pb = require('./dtypes_pb.js');
goog.object.extend(proto, dtypes_pb);
goog.exportSymbol('proto.formula_parser.FormulaParserRequest', null, global);
goog.exportSymbol('proto.formula_parser.FormulaParserResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.formula_parser.FormulaParserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.formula_parser.FormulaParserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.formula_parser.FormulaParserRequest.displayName = 'proto.formula_parser.FormulaParserRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.formula_parser.FormulaParserResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.formula_parser.FormulaParserResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.formula_parser.FormulaParserResponse.displayName = 'proto.formula_parser.FormulaParserResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.formula_parser.FormulaParserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.formula_parser.FormulaParserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.formula_parser.FormulaParserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.formula_parser.FormulaParserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    formula: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.formula_parser.FormulaParserRequest}
 */
proto.formula_parser.FormulaParserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.formula_parser.FormulaParserRequest;
  return proto.formula_parser.FormulaParserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.formula_parser.FormulaParserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.formula_parser.FormulaParserRequest}
 */
proto.formula_parser.FormulaParserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFormula(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.formula_parser.FormulaParserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.formula_parser.FormulaParserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.formula_parser.FormulaParserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.formula_parser.FormulaParserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFormula();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string formula = 1;
 * @return {string}
 */
proto.formula_parser.FormulaParserRequest.prototype.getFormula = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.formula_parser.FormulaParserRequest} returns this
 */
proto.formula_parser.FormulaParserRequest.prototype.setFormula = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.formula_parser.FormulaParserResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.formula_parser.FormulaParserResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.formula_parser.FormulaParserResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.formula_parser.FormulaParserResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    formula: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tokens: (f = msg.getTokens()) && dtypes_pb.Tokens.toObject(includeInstance, f),
    ast: (f = msg.getAst()) && dtypes_pb.AST.toObject(includeInstance, f),
    error: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.formula_parser.FormulaParserResponse}
 */
proto.formula_parser.FormulaParserResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.formula_parser.FormulaParserResponse;
  return proto.formula_parser.FormulaParserResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.formula_parser.FormulaParserResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.formula_parser.FormulaParserResponse}
 */
proto.formula_parser.FormulaParserResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFormula(value);
      break;
    case 2:
      var value = new dtypes_pb.Tokens;
      reader.readMessage(value,dtypes_pb.Tokens.deserializeBinaryFromReader);
      msg.setTokens(value);
      break;
    case 3:
      var value = new dtypes_pb.AST;
      reader.readMessage(value,dtypes_pb.AST.deserializeBinaryFromReader);
      msg.setAst(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.formula_parser.FormulaParserResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.formula_parser.FormulaParserResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.formula_parser.FormulaParserResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.formula_parser.FormulaParserResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFormula();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTokens();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      dtypes_pb.Tokens.serializeBinaryToWriter
    );
  }
  f = message.getAst();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      dtypes_pb.AST.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string formula = 1;
 * @return {string}
 */
proto.formula_parser.FormulaParserResponse.prototype.getFormula = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.formula_parser.FormulaParserResponse} returns this
 */
proto.formula_parser.FormulaParserResponse.prototype.setFormula = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional dtypes.Tokens tokens = 2;
 * @return {?proto.dtypes.Tokens}
 */
proto.formula_parser.FormulaParserResponse.prototype.getTokens = function() {
  return /** @type{?proto.dtypes.Tokens} */ (
    jspb.Message.getWrapperField(this, dtypes_pb.Tokens, 2));
};


/**
 * @param {?proto.dtypes.Tokens|undefined} value
 * @return {!proto.formula_parser.FormulaParserResponse} returns this
*/
proto.formula_parser.FormulaParserResponse.prototype.setTokens = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.formula_parser.FormulaParserResponse} returns this
 */
proto.formula_parser.FormulaParserResponse.prototype.clearTokens = function() {
  return this.setTokens(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.formula_parser.FormulaParserResponse.prototype.hasTokens = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional dtypes.AST ast = 3;
 * @return {?proto.dtypes.AST}
 */
proto.formula_parser.FormulaParserResponse.prototype.getAst = function() {
  return /** @type{?proto.dtypes.AST} */ (
    jspb.Message.getWrapperField(this, dtypes_pb.AST, 3));
};


/**
 * @param {?proto.dtypes.AST|undefined} value
 * @return {!proto.formula_parser.FormulaParserResponse} returns this
*/
proto.formula_parser.FormulaParserResponse.prototype.setAst = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.formula_parser.FormulaParserResponse} returns this
 */
proto.formula_parser.FormulaParserResponse.prototype.clearAst = function() {
  return this.setAst(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.formula_parser.FormulaParserResponse.prototype.hasAst = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string error = 4;
 * @return {string}
 */
proto.formula_parser.FormulaParserResponse.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.formula_parser.FormulaParserResponse} returns this
 */
proto.formula_parser.FormulaParserResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.formula_parser);
