# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dtypes.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dtypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64types.proto\x12\x06\x64types\"\xc3\x02\n\x03\x41ST\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.dtypes.AstType\x12\x15\n\x08operator\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1e\n\x04left\x18\x03 \x01(\x0b\x32\x0b.dtypes.ASTH\x01\x88\x01\x01\x12\x1f\n\x05right\x18\x04 \x01(\x0b\x32\x0b.dtypes.ASTH\x02\x88\x01\x01\x12\x1e\n\targuments\x18\x05 \x03(\x0b\x32\x0b.dtypes.AST\x12\x11\n\x04name\x18\x06 \x01(\tH\x03\x88\x01\x01\x12%\n\x07refType\x18\x07 \x01(\x0e\x32\x0f.dtypes.RefTypeH\x04\x88\x01\x01\x12\x10\n\x03key\x18\x08 \x01(\tH\x05\x88\x01\x01\x12\x12\n\x05value\x18\t \x01(\x02H\x06\x88\x01\x01\x42\x0b\n\t_operatorB\x07\n\x05_leftB\x08\n\x06_rightB\x07\n\x05_nameB\n\n\x08_refTypeB\x06\n\x04_keyB\x08\n\x06_value\"e\n\x06Tokens\x12$\n\x06tokens\x18\x01 \x03(\x0b\x32\x14.dtypes.Tokens.Token\x1a\x35\n\x05Token\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07subtype\x18\x03 \x01(\t*\x98\x01\n\x07\x41stType\x12\x0f\n\x0b\x41ST_UNKNOWN\x10\x00\x12\x19\n\x15\x41ST_BINARY_EXPRESSION\x10\x01\x12\x12\n\x0e\x41ST_CELL_RANGE\x10\x02\x12\x10\n\x0c\x41ST_FUNCTION\x10\x03\x12\x0c\n\x08\x41ST_CELL\x10\x04\x12\x0e\n\nAST_NUMBER\x10\x05\x12\x0f\n\x0b\x41ST_LOGICAL\x10\x06\x12\x0c\n\x08\x41ST_TEXT\x10\x07*M\n\x07RefType\x12\x0f\n\x0bREF_UNKNOWN\x10\x00\x12\x10\n\x0cREF_RELATIVE\x10\x01\x12\x10\n\x0cREF_ABSOLUTE\x10\x02\x12\r\n\tREF_MIXED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dtypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASTTYPE']._serialized_start=454
  _globals['_ASTTYPE']._serialized_end=606
  _globals['_REFTYPE']._serialized_start=608
  _globals['_REFTYPE']._serialized_end=685
  _globals['_AST']._serialized_start=25
  _globals['_AST']._serialized_end=348
  _globals['_TOKENS']._serialized_start=350
  _globals['_TOKENS']._serialized_end=451
  _globals['_TOKENS_TOKEN']._serialized_start=398
  _globals['_TOKENS_TOKEN']._serialized_end=451
# @@protoc_insertion_point(module_scope)
