# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: formula_parser.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'formula_parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dtypes_pb2 as dtypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ormula_parser.proto\x12\x0e\x66ormula_parser\x1a\x0c\x64types.proto\"\'\n\x14\x46ormulaParserRequest\x12\x0f\n\x07\x66ormula\x18\x01 \x01(\t\"\x8e\x01\n\x15\x46ormulaParserResponse\x12\x0f\n\x07\x66ormula\x18\x01 \x01(\t\x12#\n\x06tokens\x18\x02 \x01(\x0b\x32\x0e.dtypes.TokensH\x00\x88\x01\x01\x12\x1d\n\x03\x61st\x18\x03 \x01(\x0b\x32\x0b.dtypes.ASTH\x01\x88\x01\x01\x12\r\n\x05\x65rror\x18\x04 \x01(\tB\t\n\x07_tokensB\x06\n\x04_ast2n\n\rFormulaParser\x12]\n\x0cParseFormula\x12$.formula_parser.FormulaParserRequest\x1a%.formula_parser.FormulaParserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'formula_parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORMULAPARSERREQUEST']._serialized_start=54
  _globals['_FORMULAPARSERREQUEST']._serialized_end=93
  _globals['_FORMULAPARSERRESPONSE']._serialized_start=96
  _globals['_FORMULAPARSERRESPONSE']._serialized_end=238
  _globals['_FORMULAPARSER']._serialized_start=240
  _globals['_FORMULAPARSER']._serialized_end=350
# @@protoc_insertion_point(module_scope)
