architecture-beta
    group aws(logos:aws)[AWS Cloud Environment]
    group network(aws:res-amazon-vpc-virtual-private-cloud-vpc)[VPC Networking] in aws
    group compute(logos:aws-ec2)[EC2 Swarm Nodes] in aws
    group storage(logos:aws)[EFS Shared Storage] in aws
    group security(logos:aws-iam)[Security and IAM] in aws
    %% group iac(logos:terraform)[IaC Tooling]

    service client(internet)[Internet Traffic]

    service igw(aws:res-amazon-vpc-internet-gateway)[Internet Gateway] in network
    service rt(aws:res-amazon-vpc-virtual-private-cloud-vpc)[Route Table and Subnet] in network
    service sg(aws:res-amazon-vpc-virtual-private-cloud-vpc)[Swarm Security Group] in network

    service manager(logos:aws-ec2)[Manager Nodes] in compute
    service worker(logos:aws-ec2)[Worker Nodes] in compute

    service efs(aws:arch-amazon-efs)[Elastic File System] in storage

    service iam(logos:aws-iam)[IAM Instance Profile] in security
    service ssm(aws:arch-aws-systems-manager)[Systems Manager] in security

    %% service terraform(logos:terraform)[Terraform] in iac
    %% service ansible(logos:ansible)[Ansible] in iac

    junction j1 in storage
    junction j2 in network

    client: B --> T: igw
    igw: B --> T: rt
    rt: B --> T: sg

    sg: R --> L: j2
    j2: B --> T: worker

    sg: B --> T: manager
    manager: R --> L: worker

    manager: L --> R: iam
    iam: T --> B: ssm

    manager: B --> T: efs
    worker: B --> T: j1
    j1: L --> R: efs

    %% terraform: R --> L: manager
    %% terraform: B --> T: worker
    %% ansible: L --> R: manager
    %% ansible: B --> T: worker
