"""Create the database for users and projects

Revision ID: 38bf5c58d163
Revises:
Create Date: 2026-02-18 18:00:59.232132

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38bf5c58d163"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("db_host", sa.String(), nullable=True),
        sa.Column("db_port", sa.String(), nullable=True),
        sa.Column("db_user", sa.String(), nullable=True),
        sa.Column("db_password", sa.String(), nullable=True),
        sa.Column("db_name", sa.String(), nullable=True),
        sa.Column("db_netloc", sa.String(), nullable=True),
        sa.Column("db_params", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_project_name"),
        schema="public",
    )
    op.create_index(
        "idx_project_name", "project", ["name"], unique=False, schema="public"
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("SUDO", "USER", name="user_role_enum", schema="public"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="user_status_enum", schema="public"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("password", sa.String(), nullable=False),
        sa.CheckConstraint(
            "email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'",
            name="ck_user_email_format",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_user_email"),
        schema="public",
    )
    op.create_index("idx_user_email", "user", ["email"], unique=False, schema="public")
    op.create_index("idx_user_name", "user", ["name"], unique=False, schema="public")
    op.create_index("idx_user_role", "user", ["role"], unique=False, schema="public")
    op.create_index(
        "idx_user_status", "user", ["status"], unique=False, schema="public"
    )
    op.create_table(
        "user_project",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "SHARED",
                "VIEWER",
                name="user_project_type_enum",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["public.project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "project_id"),
        schema="public",
    )
    op.create_index(
        "idx_user_project_project_id",
        "user_project",
        ["project_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "idx_user_project_role", "user_project", ["role"], unique=False, schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_project_role", table_name="user_project", schema="public")
    op.drop_index(
        "idx_user_project_project_id", table_name="user_project", schema="public"
    )
    op.drop_table("user_project", schema="public")
    op.drop_index("idx_user_status", table_name="user", schema="public")
    op.drop_index("idx_user_role", table_name="user", schema="public")
    op.drop_index("idx_user_name", table_name="user", schema="public")
    op.drop_index("idx_user_email", table_name="user", schema="public")
    op.drop_table("user", schema="public")
    op.drop_index("idx_project_name", table_name="project", schema="public")
    op.drop_table("project", schema="public")
    # ### end Alembic commands ###

    # Drop the enums
    op.execute("DROP TYPE public.user_role_enum")
    op.execute("DROP TYPE public.user_status_enum")
    op.execute("DROP TYPE public.user_project_type_enum")
