"""Create new table for idempotency

Revision ID: 8f1d929cc229
Revises: 38bf5c58d163
Create Date: 2026-02-25 20:13:33.670311

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f1d929cc229"
down_revision: Union[str, Sequence[str], None] = "38bf5c58d163"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_tasks",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PUBLISHED",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="task_status_enum",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("file_hash", sa.String(), nullable=True),
        sa.Column(
            "task_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["public.project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.user.id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
        schema="public",
    )
    op.create_index(
        "idx_idempotency_key",
        "upload_tasks",
        ["idempotency_key"],
        unique=False,
        schema="public",
    )
    op.create_index(
        "idx_project_id", "upload_tasks", ["project_id"], unique=False, schema="public"
    )
    op.create_index(
        "idx_status", "upload_tasks", ["status"], unique=False, schema="public"
    )
    op.create_index(
        "idx_user_id", "upload_tasks", ["user_id"], unique=False, schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_id", table_name="upload_tasks", schema="public")
    op.drop_index("idx_status", table_name="upload_tasks", schema="public")
    op.drop_index("idx_project_id", table_name="upload_tasks", schema="public")
    op.drop_index("idx_idempotency_key", table_name="upload_tasks", schema="public")
    op.drop_table("upload_tasks", schema="public")
    # ### end Alembic commands ###

    op.execute("DROP TYPE public.task_status_enum")
