name: CI - API Tests
on:
  pull_request:
    branches:
      - main
      - staging
      - development
    paths:
      - apps/backend/api/**
      - packages/messaging-utils/messaging-utils-py/**
      - .github/actions/run-unit-tests/**
      - .github/workflows/ci-api-tests.yml

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: api_db

    steps:
      # One dependency (pyaegis) needs clang to be installed,
      # so, just in case it is not installed in the runner, we will install it before running the tests
      - name: Install Clang
        run: |
          sudo apt update
          sudo apt install -y clang

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/run-unit-tests
        with:
          service_name: "api"
          env_example_file: "apps/backend/api/.env.example"
          postgres_username: "admin"
          postgres_password: "admin"
          postgres_db: "api_db"
      - name: Build Docker Image
        uses: ./.github/actions/build-docker-image
        with:
          service_name: "api"
          verify_image: "true"
          push_image: "false"
