name: CI - Excel Reader Tests
on:
  pull_request:
    branches:
      - main
      - staging
      - development
    paths:
      - apps/backend/parsers/excel-reader/**
      - packages/proto-utils/proto-utils-py/**
      - .github/actions/run-unit-tests/**
      - .github/workflows/ci-excel-reader-tests.yml

jobs:
  excel_reader-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/run-unit-tests
        with:
          service_name: "excel-reader"
          env_example_file: "apps/backend/parsers/excel-reader/.env.example"
      - name: Build Docker Image
        uses: ./.github/actions/build-docker-image
        with:
          service_name: "excel-reader"
          verify_image: "true"
          push_image: "false"